' MK-61 variant for Nintendo Switch / Smile BASIC 4
' NOTE: this is a practical SB4 frontend implementation with MK-61-style RPN behavior,
'       intended for daily usage on-device. It is not bit-exact RTL emulation.
'
' Controls (default, full controller style):
'  Left stick / D-pad : move cursor on virtual key matrix
'  A (#B_RRIGHT)      : press selected key
'  B (#B_RDOWN)       : CX
'  X (#B_RUP)         : F shift
'  Y (#B_RLEFT)       : K shift
'  L (#B_L1)          : cycle RAD/DEG/GRD
'  R (#B_R1)          : EXE (V)
'  ZL (#B_S1)         : F shift
'  ZR (#B_S2)         : K shift
'
' ---- State ----
OPTION STRICT
X=0:Y=0:Z=0:T=0
EDITING=0:SHIFTF=0:SHIFTK=0
MODE=0
CURR=0:CURC=0
STATUS$="READY"
EDIT$=""
RET$=""
PI#=3.14159265358979

DIM KEY$[3,10]
DIM KEYF$[3,10]
DIM KEYK$[3,10]

GOSUB @INIT_KEYS
GOSUB @RESET_STATE

@MAIN
 GOSUB @POLL_INPUT
 GOSUB @RENDER
 VSYNC 1
GOTO @MAIN

@INIT_KEYS
 ' Base layout by MK-61 matrix rows (D2..D11)
 KEY$[0,0]="0":KEY$[0,1]="1":KEY$[0,2]="2":KEY$[0,3]="3":KEY$[0,4]="4"
 KEY$[0,5]="5":KEY$[0,6]="6":KEY$[0,7]="7":KEY$[0,8]="8":KEY$[0,9]="9"
 KEY$[1,0]="+":KEY$[1,1]="-":KEY$[1,2]="*":KEY$[1,3]="/":KEY$[1,4]="POW"
 KEY$[1,5]=".":KEY$[1,6]="/-/":KEY$[1,7]="VP":KEY$[1,8]="CX":KEY$[1,9]="V"
 KEY$[2,0]="SP":KEY$[2,1]="BP":KEY$[2,2]="VO":KEY$[2,3]="PP":KEY$[2,4]="X2P"
 KEY$[2,5]="SHG>":KEY$[2,6]="P2X":KEY$[2,7]="<SHG":KEY$[2,8]="K":KEY$[2,9]="F"

 ' F-shift useful subset
 KEYF$[0,7]="SIN":KEYF$[0,8]="COS":KEYF$[0,9]="TG"
 KEYF$[1,0]="PI":KEYF$[1,1]="SQRT":KEYF$[1,2]="X2":KEYF$[1,3]="INVX":KEYF$[1,4]="POW"

 ' K-shift useful subset
 KEYK$[0,4]="ABS":KEYK$[0,7]="INT":KEYK$[1,7]="XOR":KEYK$[1,8]="INV"
RETURN

@RESET_STATE
 X=0:Y=0:Z=0:T=0
 EDITING=0
 SHIFTF=0
 SHIFTK=0
 MODE=0  ' 0=RAD, 1=DEG, 2=GRD
 CURR=0
 CURC=0
 STATUS$="READY"
 EDIT$=""
RETURN

@POLL_INPUT
 IF BUTTON(0,#B_LLEFT,2) THEN CURC=(CURC+9) MOD 10:STATUS$="CURSOR":GOTO @POLL_DONE
 IF BUTTON(0,#B_LRIGHT,2) THEN CURC=(CURC+1) MOD 10:STATUS$="CURSOR":GOTO @POLL_DONE
 IF BUTTON(0,#B_LUP,2) THEN CURR=(CURR+2) MOD 3:STATUS$="CURSOR":GOTO @POLL_DONE
 IF BUTTON(0,#B_LDOWN,2) THEN CURR=(CURR+1) MOD 3:STATUS$="CURSOR":GOTO @POLL_DONE

 IF BUTTON(0,#B_RUP,2) THEN SHIFTF=1:SHIFTK=0:STATUS$="F":GOTO @POLL_DONE
 IF BUTTON(0,#B_RLEFT,2) THEN SHIFTK=1:SHIFTF=0:STATUS$="K":GOTO @POLL_DONE
 IF BUTTON(0,#B_S1,2) THEN SHIFTF=1:SHIFTK=0:STATUS$="F":GOTO @POLL_DONE
 IF BUTTON(0,#B_S2,2) THEN SHIFTK=1:SHIFTF=0:STATUS$="K":GOTO @POLL_DONE

 IF BUTTON(0,#B_L1,2) THEN MODE=(MODE+1) MOD 3:STATUS$="MODE":GOTO @POLL_DONE
 IF BUTTON(0,#B_R1,2) THEN GOSUB @PRESS_V:STATUS$="V":GOTO @POLL_DONE

 IF BUTTON(0,#B_RDOWN,2) THEN GOSUB @PRESS_CX:STATUS$="CX":GOTO @POLL_DONE

 IF BUTTON(0,#B_RRIGHT,2) THEN
  GOSUB @PRESS_SELECTED
  GOTO @POLL_DONE
 ENDIF

@POLL_DONE
RETURN

@PRESS_SELECTED
 TOK$=KEY$[CURR,CURC]
 IF SHIFTF THEN
  IF KEYF$[CURR,CURC]<>"" THEN TOK$=KEYF$[CURR,CURC]
  SHIFTF=0:SHIFTK=0
 ELSEIF SHIFTK THEN
  IF KEYK$[CURR,CURC]<>"" THEN TOK$=KEYK$[CURR,CURC]
  SHIFTK=0:SHIFTF=0
 ENDIF
 GOSUB @PRESS_TOKEN
RETURN

@PRESS_TOKEN
 IF TOK$=="F" THEN SHIFTF=1:SHIFTK=0:RETURN
 IF TOK$=="K" THEN SHIFTK=1:SHIFTF=0:RETURN
 IF TOK$=="VP" THEN TOK$="V"

 IF TOK$=="0" OR TOK$=="1" OR TOK$=="2" OR TOK$=="3" OR TOK$=="4" OR TOK$=="5" OR TOK$=="6" OR TOK$=="7" OR TOK$=="8" OR TOK$=="9" THEN
  IF EDITING==0 THEN EDIT$=""
  EDIT$=EDIT$+TOK$
  EDITING=1
  STATUS$="NUM"
  RETURN
 ENDIF

 IF TOK$=="." THEN
  IF EDITING==0 THEN EDIT$="0"
  IF INSTR(EDIT$,".")==0 THEN EDIT$=EDIT$+"."
  EDITING=1
  STATUS$="DOT"
  RETURN
 ENDIF

 IF TOK$=="/-/" THEN
  IF EDITING THEN
  IF LEFT$(EDIT$,1)=="-" THEN EDIT$=MID$(EDIT$,2) ELSE EDIT$="-"+EDIT$
  ELSE
   X=-X
  ENDIF
  STATUS$="SIGN"
  RETURN
 ENDIF

 IF TOK$=="CX" THEN
  GOSUB @PRESS_CX
  RETURN
 ENDIF

 IF TOK$=="V" THEN
  GOSUB @PRESS_V
  RETURN
 ENDIF

 GOSUB @COMMIT_EDIT

 IF TOK$=="+" THEN X=Y+X:Y=Z:Z=T:STATUS$="+":RETURN
 IF TOK$=="-" THEN X=Y-X:Y=Z:Z=T:STATUS$="-":RETURN
 IF TOK$=="*" THEN X=Y*X:Y=Z:Z=T:STATUS$="*":RETURN
 IF TOK$=="/" THEN
  IF X==0 THEN STATUS$="DIV0" ELSE X=Y/X:Y=Z:Z=T:STATUS$="/"
  RETURN
 ENDIF
 IF TOK$=="POW" THEN X=Y^X:Y=Z:Z=T:STATUS$="POW":RETURN
 IF TOK$=="PI" THEN X=PI#:STATUS$="PI":RETURN
 IF TOK$=="SQRT" THEN IF X<0 THEN STATUS$="SQRT?" ELSE X=SQR(X):STATUS$="SQRT":RETURN
 IF TOK$=="X2" THEN X=X*X:STATUS$="X2":RETURN
 IF TOK$=="INVX" THEN IF X==0 THEN STATUS$="INV?" ELSE X=1/X:STATUS$="INVX":RETURN

 IF TOK$=="SIN" THEN GOSUB @TO_RAD:X=SIN(X):STATUS$="SIN":RETURN
 IF TOK$=="COS" THEN GOSUB @TO_RAD:X=COS(X):STATUS$="COS":RETURN
 IF TOK$=="TG" THEN GOSUB @TO_RAD:X=TAN(X):STATUS$="TG":RETURN

 STATUS$=TOK$
RETURN

@TO_RAD
 IF MODE==1 THEN X=X*PI#/180
 IF MODE==2 THEN X=X*PI#/200
RETURN

@PRESS_CX
 EDITING=0
 EDIT$=""
 X=0
 STATUS$="CX"
RETURN

@PRESS_V
 GOSUB @COMMIT_EDIT
 T=Z:Z=Y:Y=X
 STATUS$="V"
RETURN

@COMMIT_EDIT
 IF EDITING THEN
  X=VAL(EDIT$)
  EDITING=0
  EDIT$=""
 ENDIF
RETURN

@MODE_NAME$
 IF MODE==0 THEN RET$="RAD":RETURN
 IF MODE==1 THEN RET$="DEG":RETURN
 RET$="GRD"
RETURN

@CUR_TOKEN$
 RET$=KEY$[CURR,CURC]
RETURN

@FMTX$
 IF EDITING THEN RET$=EDIT$:RETURN
 RET$=STR$(X)
RETURN

@RENDER
 CLS
 LOCATE 0,0:PRINT "MK-61 / Smile BASIC 4"
 LOCATE 0,1:PRINT "MODE ";:GOSUB @MODE_NAME$:PRINT RET$
 LOCATE 0,2:PRINT "X=";:GOSUB @FMTX$:PRINT RET$
 LOCATE 0,3:PRINT "Y=";Y;" Z=";Z;" T=";T
 LOCATE 0,4:PRINT "F=";SHIFTF;" K=";SHIFTK;"  ";STATUS$

 LOCATE 0,6:PRINT "Cursor key: ";:GOSUB @CUR_TOKEN$:PRINT RET$
 LOCATE 0,7:PRINT "A=press B=CX X=F Y=K L=mode R=V"

 FOR R=0 TO 2
  FOR C=0 TO 9
   POSX=C*3
   POSY=9+R
   LOCATE POSX,POSY
   IF R==CURR AND C==CURC THEN
    PRINT "[";LEFT$(KEY$[R,C],1);"]";
   ELSE
    PRINT " ";LEFT$(KEY$[R,C],1);" ";
   ENDIF
  NEXT
 NEXT
RETURN
